#!/bin/bash

# To be used with cquery
# Call below process compile_database.json generated by cmake and adds records for each
# header files.
#
# Result printed to stdout which in turn gets parsed by cquery. To use simple pass that
# script path (relative to project root) as cquery compilationDatabaseCommand parameter

compdb -p "$1/build" list
